# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "XMPP Providers"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://providers.xmpp.net/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = ""
  homepage = ""
